apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask
  name: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask
    spec:
      containers:
      - image: farazff/clocks:1.1
        name: clock
        resources: {}
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: /project/config.json
            subPath: config.json
            name: config-map
      volumes:
        - name: config-map
          configMap:
            name: flask-config
status: {}